version: '3'

includes:
  docker: ./taskfiles/docker.yml
  db: ./taskfiles/duckdb.yml
  pipeline: ./taskfiles/pipeline.yml
  py: ./taskfiles/python.yml
  admin: ./taskfiles/admin.yml
  web: ./taskfiles/web.yml

tasks:
  default:
    desc: Visa tillgängliga kommandon
    cmds:
      - task --list

  init:
    desc: Initiera hela projektet (Python, Docker, etc.)
    cmds:
      - task py:install
      - task db:init
      - echo "Projekt initierat!"

  run:
    desc: Kör hela pipelinen
    cmds:
      - task pipeline:run

  clean:
    desc: Rensa genererade filer och cache
    cmds:
      - rm -rf .venv __pycache__ .pytest_cache
      - echo "Städat klart!"
