version: "3"

includes:
  py: ./taskfiles/python.yml
  admin: ./taskfiles/admin.yml
  pipeline: ./taskfiles/pipeline.yml
  release: ./taskfiles/release.yml
  qgis: ./taskfiles/qgis.yml

tasks:
  default:
    desc: Visa tillgängliga kommandon
    cmds:
      - task --list

  hq:
    desc: Starta Harlequin (DuckDB GUI)
    cmds:
      - uv run harlequin data/warehouse.duckdb

  hq_f:
    desc: Öppna Parquet-fil/Duckdb-fil i Harlequin (task hq_parquet -- <fil>)
    cmds:
      - uv run harlequin {{.CLI_ARGS}}

  sf:
    desc: Starta Superfile (filhanterare)
    cmds:
      - superfile
