version: "3"

includes:
  py: ./taskfiles/python.yml
  admin: ./taskfiles/admin.yml
  pipeline: ./taskfiles/pipeline.yml
  release: ./taskfiles/release.yml
  qgis: ./taskfiles/qgis.yml

tasks:
  default:
    desc: Visa tillgängliga kommandon
    cmds:
      - task --list

  hq:
    desc: Starta Harlequin (DuckDB GUI)
    cmds:
      - uv run harlequin data/warehouse.duckdb

  hq_parquet:
    desc:
    cmds:
      - uv run harlequin /home/mate01/g-etl_test/data/raw/underlag_taktplan.parquet

  sf:
    desc: Starta Superfile (filhanterare)
    cmds:
      - superfile
