version: "3"

tasks:
  run:
    desc: Kör hela pipelinen (extract + transform)
    cmds:
      - uv run python -m scripts.pipeline

  extract:
    desc: Kör bara extract (hämta data)
    cmds:
      - uv run python -m scripts.pipeline --extract-only

  transform:
    desc: Kör bara transform (SQL-filer)
    cmds:
      - uv run python -m scripts.pipeline --transform-only

  dataset:
    desc: Kör specifikt dataset (task pipeline:dataset -- naturreservat)
    cmds:
      - uv run python -m scripts.pipeline --dataset {{.CLI_ARGS}}

  type:
    desc: Kör datasets av viss typ (task pipeline:type -- skogsstyrelsen_gpkg)
    cmds:
      - uv run python -m scripts.pipeline --type {{.CLI_ARGS}}

  types:
    desc: Lista tillgängliga dataset-typer
    cmds:
      - uv run python -m scripts.pipeline --list-types

  export:kepler:
    desc: Exportera H3-data till CSV för Kepler.gl (en fil per mart-tabell)
    cmds:
      - uv run python scripts/export_h3.py --per-table

  export:geojson:
    desc: Exportera H3-data till GeoJSON
    cmds:
      - uv run python scripts/export_h3.py --format geojson --limit 10000

  export:html:
    desc: Exportera H3-data till interaktiv HTML-karta
    cmds:
      - uv run python scripts/export_h3.py --format html --limit 5000

  export:parquet:
    desc: Exportera H3-data till GeoParquet
    cmds:
      - uv run python scripts/export_h3.py --format parquet
