version: "3"

tasks:
  run:
    desc: Kör hela pipelinen (extract + transform)
    cmds:
      - uv run python -m g_etl.pipeline

  extract:
    desc: Kör bara extract (hämta data)
    cmds:
      - uv run python -m g_etl.pipeline --extract-only

  transform:
    desc: Kör bara transform (SQL-filer)
    cmds:
      - uv run python -m g_etl.pipeline --transform-only

  dataset:
    desc: Kör specifikt dataset (task pipeline:dataset -- naturreservat)
    cmds:
      - uv run python -m g_etl.pipeline --dataset {{.CLI_ARGS}}

  type:
    desc: Kör datasets av viss typ (task pipeline:type -- skogsstyrelsen_gpkg)
    cmds:
      - uv run python -m g_etl.pipeline --type {{.CLI_ARGS}}

  types:
    desc: Lista tillgängliga dataset-typer
    cmds:
      - uv run python -m g_etl.pipeline --list-types

  export:kepler:
    desc: Exportera H3-data till CSV för Kepler.gl
    cmds:
      - uv run python -m g_etl.export_h3 --format csv

  export:geojson:
    desc: Exportera H3-data till GeoJSON
    cmds:
      - uv run python -m g_etl.export_h3 --format geojson

  export:html:
    desc: Exportera H3-data till interaktiv HTML-karta
    cmds:
      - uv run python -m g_etl.export_h3 --format html

  export:parquet:
    desc: Exportera H3-data till GeoParquet
    cmds:
      - uv run python -m g_etl.export_h3 --format parquet

  export:gpkg:
    desc: Exportera H3-data till GeoPackage (bäst för QGIS)
    cmds:
      - uv run python -m g_etl.export_h3 --format gpkg

  export:fgb:
    desc: Exportera H3-data till FlatGeobuf (snabb streaming)
    cmds:
      - uv run python -m g_etl.export_h3 --format fgb
